name: Space-Xit-Compiler

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Instalar Theos
        run: |
          export THEOS=~/theos
          git clone --recursive https://github.com/theos/theos.git $THEOS
          echo "THEOS=$THEOS" >> $GITHUB_ENV

      - name: Instalar SDK corrigido
        run: |
          mkdir -p ~/theos/sdks
          curl -L https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz | tar -xf - -C ~/theos/sdks
          
      - name: Compilando SpaceXit Dylib
        run: |
          make package FINALPACKAGE=1
        env:
          THEOS: ~/theos

      - name: Armazenar Dylib Pronta
        uses: actions/upload-artifact@v4
        with:
          name: SpaceXit-Output
          path: packages/*.deb
