name: SpaceXit_V4_Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git dpkg-dev xz-utils
          sudo curl -kL "https://github.com/theos/binaries/raw/master/linux/x86_64/ldid" -o /usr/local/bin/ldid
          sudo chmod +x /usr/local/bin/ldid
          git clone --recursive https://github.com/theos/theos.git ~/theos

      - name: Baixar SDK Real (Sem 404)
        run: |
          mkdir -p ~/theos/sdks
          # Usando o link do repositório xybp888 que está ativo
          curl -kL "https://github.com/xybp888/iOS-SDKs/raw/master/iPhoneOS14.5.sdk.tar.xz" -o ~/theos/sdks/sdk.tar.xz
          cd ~/theos/sdks/
          tar -xf sdk.tar.xz && rm sdk.tar.xz

      - name: Compilar dylib
        run: |
          export THEOS=~/theos
          export PATH=$THEOS/bin:$PATH
          make clean package FINALPACKAGE=1

      - name: Link de Download
        run: |
          echo "BAIXE SUA DYLIB AQUI:"
          curl --upload-file packages/*.deb https://transfer.sh/SpaceXitV4.deb
